#!/bin/bash

knockpy --set apikey-virustotal=89d6092ffcd7b9638ee19601509c9ff7c4b05ce789fcb68124213c05f361377c
wordlist in main dirctory of knockpy
subfinder apikeys
dirsearch wordlist
tools:
- knockpy
- shuffledns
- massdns
- subfinder
- assetfinder
- httpx
- dirsearch
- wappalyzer##
- GitDorker
- naabu
- subover
- gau
- brutespray
- nuclei & nuclei templates
- jaeles & jaeles signtures 
- Gxss
- dalfox
- smuggler
- clickjacking##
- s3brute
- gf & GF-Patterns
- nmap
- subjs
- qsreplace
- linux commands[sed, sort, cat, mv, python3, wget, mkdir, ls]
errors with fuzz cors